---
templatelink: "https://raw.githubusercontent.com/jhorn-redhat/openshift-ansible-contrib/master/reference-architecture/azure-ansible/3.6/azuredeploy.json"
#template: "{{ playbook_dir }}/../../azuredeploy.json"
templatelink: "https://openshiftrefarch.blob.core.windows.net/ocp-lab/azuredeploy.json"
numberofnodes: 3
image: "rhel"
mastervmsize: "Standard_DS4_v2"
infranodesize: "Standard_DS4_v2"
nodevmsize: "Standard_DS4_v2"
location: "westus"
openshiftsdn: "redhat/openshift-ovs-multitenant"
metrics: true
logging: true
opslogging: false
fqdn: "false"
masterurl: "false"
masterprivateip: "false"
bastionprivateip: "false"
routercertdata: "false"
routerkeydata: "false"
routercadata: "false"
mastercertdata: "false"
masterkeydata: "false"
mastercadata: "false"
customdns: "false"
autoinstall: "true"
subscriptionbrokerpoolid: "{{ subscriptionpoolid }}"
# base64-encoded version of
# [{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
identityproviders: "W3snbmFtZSc6ICdodHBhc3N3ZF9hdXRoJywgJ2xvZ2luJzogJ3RydWUnLCAnY2hhbGxlbmdlJzogJ3RydWUnLCAna2luZCc6ICdIVFBhc3N3ZFBhc3N3b3JkSWRlbnRpdHlQcm92aWRlcicsICdmaWxlbmFtZSc6ICcvZXRjL29yaWdpbi9tYXN0ZXIvaHRwYXNzd2QnfV0K"
